name: widgetbook_workspace
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.0.1
  auravibes_ui: 0.0.2
  widgetbook: ^3.20.2
  widgetbook_annotation: ^3.10.0
  collection: ^1.19.1

dev_dependencies:
  build_runner: ^2.11.1
  flutter_lints: ^6.0.0
  widgetbook_generator: ^3.20.1

flutter:
  uses-material-design: true
version: 0.1.0
